### ISSUE TITLE
建议将 AdGuard DNS fliter 转换

### ISSUE THREAD

**Issue by luzhaohui** [geekdada/surge-list#1]
根据 AdGuard 官方介绍，DNS过滤器 — 此过滤器由其他几个过滤器 (AdGuard 基础过滤器、社交媒体过滤器、防跟踪保护过滤器、移动广告过滤器、EasyList 和 EasyPrivacy) 组成，并经过简化，以便更好地与 DNS 级别的广告拦截兼容。AdGuard DNS 服务器使用此过滤器来拦截广告和跟踪。

这样，domain-set 可以简化为 dns-fliter、chinese-fliter、adaway、neohosts，有这几个基本够了。

**Comment by geekdada** [comment]
已增加
