### ISSUE TITLE
关于social-media-filter.txt更新问题

### ISSUE THREAD

**Issue by mangoclover** [geekdada/surge-list#2]
RT，geekdada大佬，我看了下social-media-filter.txt的上游列表最近都有更新，为啥咱们这边的显示最近一次是4个月前更新的。
具体见https://github.com/AdguardTeam/FiltersRegistry/tree/master/filters/filter_4_Social

**Comment by geekdada** [comment]
Social 规则内包含用于 AdBlock 的 DOM 元素拦截规则，这部分规则无法被转换为域名规则，所以这里一直没有更新。

你放心，这个项目是每日自动生成，不会有遗漏。

**Comment by mangoclover** [comment]
好的，了解了，谢谢释疑。

**Comment by mangoclover** [comment]
> Social 规则内包含用于 AdBlock 的 DOM 元素拦截规则，这部分规则无法被转换为域名规则，所以这里一直没有更新。
> 
> 你放心，这个项目是每日自动生成，不会有遗漏。

好的，了解了，感谢释疑。
