### ISSUE TITLE
关于Apple 其他自选部分的迷惑

### ISSUE THREAD

**Issue by aoaim** [geekdada/surge-list#3]
dada 你好！用了很久你的规则了，觉得很满意，但是有点点迷惑的地方。

我是在中国大陆使用美国区 Apple ID。看到你的[这篇博文](https://royli.dev/blog/2019/better-proxy-rules-for-apple-services)之后我开始考虑到分流 Apple 策略组的问题。在 apple.tpl 中的 Apple 其他自选 部分我有点迷惑，这部分是应该走美国区代理，还是亦可以直连？此处的自选是这个意思么？因为这里自选部分有两个规则杀伤力巨大，一个是 [DOMAIN-SUFFIX,apple,{{ api_rule }}](https://github.com/geekdada/surge-list/blob/4d5e5dd9084d3ff115889b89ed602595f88bec49/surgio-snippet/apple.tpl#L158) ，另一个是 [DOMAIN-SUFFIX,apple.com,{{ api_rule }}](https://github.com/geekdada/surge-list/blob/4d5e5dd9084d3ff115889b89ed602595f88bec49/surgio-snippet/apple.tpl#L163)，会匹配上大部分的 apple 连接。

另外，如果可以，希望 dada 加入 1Hosts(Lite) 的策略组，项目地址在 https://github.com/badmojr/1Hosts，我觉得 1Hosts 在去广告上非常好用。 

谢谢！

**Comment by geekdada** [comment]
美国区的 Apple ID 意味着已经确定的域名以及其它不确定域名（更广泛的匹配规则）应该走代理。

维护不同的规则库工作量巨大，这里不会加入，抱歉。

**Comment by aoaim** [comment]
明白。谢谢 dada！新年快乐
