### ISSUE TITLE
DOMAIN-SET 格式问题

### ISSUE THREAD

**Issue by mieqq** [geekdada/surge-list#4]
- DOMAIN-SET 与 RULE-SET 改为强校验，当文件中包含无效行时将导致整个规则集无效，以避免误用产生问题

Surge builds 3145 对域名集等开启了强校验，含有通配符的域名将会被认为无效行导致失效，可以的话希望作者能兼容下，谢谢。

**Comment by geekdada** [comment]
修复了，感谢汇报
